name = "ISODATA"
uuid = "43280de6-1c93-41f6-a23a-7d39c20bc59b"
authors = ["Noah Gardner <ngngardner@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
